# Generated by Django 4.2.13 on 2024-07-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='cep',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='state',
            field=models.CharField(default='', max_length=256),
        ),
    ]
