# Generated by Django 4.2 on 2024-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_avaliationsbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliationsbook',
            name='avaliation',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
