# Generated by Django 4.2 on 2024-06-12 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0005_alter_avaliationsbook_avaliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliationsbook',
            name='user',
            field=models.ForeignKey(blank=True, default='Anonymous', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
