# Generated by Django 4.2.13 on 2024-07-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_alter_avaliationsbook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birthday',
        ),
    ]
