# Generated by Django 4.2.13 on 2024-07-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_remove_author_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='images',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
